FROM wodby/php:latest

# Installing dependencies for the PHP modules
#RUN apt-get update && \
#    apt-get install -y zip curl libcurl3-dev libzip-dev libpng-dev libonig-dev libxml2-dev sendmail

# Configure PHP-FPM
#COPY docker/php/php.ini /etc/php.ini

# Install Composer so it's available
#RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer